apiVersion: cluster.k8s.io/v1alpha1
kind: MachineDeployment
metadata:
  annotations:
    k8c.io/operating-system-profile: osp-ubuntu
    machinedeployment.clusters.k8s.io/revision: "1"
    cluster.k8s.io/cluster-api-autoscaler-node-group-min-size: '1'
    cluster.k8s.io/cluster-api-autoscaler-node-group-max-size: '5'
  name: k1-vsphere-new-pool-2
  namespace: kube-system
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      workerset: k1-vsphere-new-pool-2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workerset: k1-vsphere-new-pool-2
      namespace: kube-system
    spec:
      metadata:
        creationTimestamp: null
        labels:
          workerset: k1-vsphere-new-pool-2
      providerSpec:
        value:
          caPublicKey: ""
          cloudProvider: vsphere
          cloudProviderSpec:
            allowInsecure: true
            cluster: Kubermatic
            cpus: 2
            datacenter: Hamburg
            datastore: vsan
            datastoreCluster: ""
            diskSizeGB: 10
            folder: Kubermatic-PS
            memoryMB: 2048
            resourcePool: ""
            templateVMName: kkp-ubuntu-22.04
            vmNetName: Default Network
          operatingSystem: ubuntu
          operatingSystemSpec:
            distUpgradeOnBoot: false
          sshPublicKeys:
          - |
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCloj8OvReuuOXtECaMo1iZD8q8newJ9hWZSxIiwOG2406uOueYOxBleb85Jl231YWWjocj6fqExvZBzsQQlrad4fy6oDL5sKZyngtkCZnWcq1DsWn8Sgas9lw2+KS67EXO/P5SHhJSOrqyU6ciktX0WViPvVqb6DnK3RepFh6Xnyl0Q/0RnpSCTomyKK2PfNsv8e80AnfxA1CtnRfeexgwiKtQUPzkEdCG1ABcdZZru3m0y7y1qR0MdYYZIK+bycacngvJCJyp8gnIXHU8dDZanHL2WGOcCpd/gjwM6iryr6IhlCZXw++PRGK1aErtvKDH7oaAMLW8qFK4+bpMdeytd4Viw/g3SH3Q7ows2xl6NTaU2F0PTXD+qAY2xna1eemet1txl1oP6KQJ2Rqc5rNU3/auhdK4PaU22D8Z2XF7gOrsoQB7dqW0BBDHg/ftVNb9BgOHGkYvxSsCavcqX3joUyFjHzhv+sD1WiOPvfRqV4fQ8h47ERvD3QXuBn+5YKeKp/0sjSCypIdK02FAFa2NxN2tEoh7wdCBX9enFU3UT7jfeW5Pf98Z6ao9hiAF80J5FIM21sMG3E3dAMb2tr8Gc8jM5QdWO4rJkG9j5v2d1umLkSxm7pN4Mxw/AE02jYNEblm9i/Pbzg8wqa9gw2gubO7A8qoKVtA1xlOnDVB+0Q== tobi@loodse.com
      versions:
        kubelet: 1.24.11
