apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: '1.27.11'
cloudProvider:
  gce: {}
  cloudConfig: |
    [global]
    regional = true
machineController:
  deploy: false
addons:
  enable: true
  addons:
  - name: default-storage-class