apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: '1.22.5'
containerRuntime:
  containerd: {}  
cloudProvider:
  gce: {}
  cloudConfig: |
    [global]
    regional = true